### ISSUE TITLE
Moodle 3.2.1 - Button not working for Quiz grading Comment boxes

### ISSUE THREAD

**Issue by catchlightpro** [ecampbell/moodle-atto_wordimport#15]
I'm running Moodle 3.2.1.  Word File Import version  atto_wordimport_moodle32_2017010502.

The Button works for editors enabled on Quiz Essay question boxes.

The Button is dead with no action for a teacher commenting on or grading the essays in the green comment boxes.

Has anyone else tested this?

-Jim

**Comment by ecampbell** [comment]
I have reproduced your problem, and it seems to be caused by a JavaScript error in code. I'll take a look to see if I can fix it, but I notice that the image insert button is also limited, and inserting an image is not allowed, only referencing an external one. There is obviously some limitation imposed in this particular box, and that may affect importing Word file content too.

**Comment by catchlightpro** [comment]
Thanks for confirming the issue so quickly!  I hadn't tried that image insert button, so thanks for the alert.  If I run across additional info, I'll post back here as well.  This would be so cool if we can get this to import nice content from Word files (like a template) during essay grading and then personalize it a little more in the Atto editor.

**Comment by catchlightpro** [comment]
There are other boxes in various places that have similar restrictions. I haven't researched the Moodle forums about it yet.

Meanwhile, I used Firefox's Firebug debugger to see if anything showed up and recorded the following, hoping you might be able to use it, and it looks like the JavaScript error you referred to:

Line 239   Col  4385
TypeError: s is undefined

If <script> tags have a "type" attribute, it should equal "text/javascript" or "application/javascript". Also scripts must be parsable (syntactically correct).\

moodle/theme/yui_combo.php?3.17.2/handlebars-compiler/handlebars-compiler-min.js&m/1486061464/core/handlebars/handlebars-min.js&3.17.2/timers/timers-min.js&3.17.2/querystring-stringify/querystring-stringify-min.js&m/1486061464/editor_atto/editor/editor-min.js&m/1486061464/editor_atto/menu/menu-min.js&m/1486061464/editor_atto/plugin/plugin-min.js&m/1486061464/atto_collapse/button/button-min.js&m/1486061464/atto_title/button/button-min.js&m/1486061464/atto_bold/button/button-min.js&m/1486061464/atto_italic/button/button-min.js&m/1486061464/atto_fontcolor/button/button-min.js&m/1486061464/atto_backcolor/button/button-min.js&m/1486061464/atto_unorderedlist/button/button-min.js&m/1486061464/atto_orderedlist/button/button-min.js&m/1486061464/atto_link/button/button-min.js&m/1486061464/atto_wordimport/button/button-min.js&m/1486061464/atto_image/button/button-min.js&m/1486061464/atto_media/button/button-min.js&m/1486061464/atto_managefiles/button/button-min.js

**Comment by catchlightpro** [comment]
Tim Hunt over in Moodle Forums replied to me that this is not currently possible. [MDL-41090](https://tracker.moodle.org/browse/MDL-41090) is the feature request for enabling this featue. Vote there.

**Comment by catchlightpro** [comment]
Tim Hunt over in Moodle Forums replied to me that this is not currently possible. [MDL-41090](https://tracker.moodle.org/browse/MDL-41090) is the feature request for enabling this featue. Vote there.
