### ISSUE TITLE
Button is not disabled if editor field does not support filearea  

### ISSUE THREAD

**Issue by TubsDK** [ecampbell/moodle-atto_wordimport#16]
Some Moodle-text fields does not support embedding of files eg the assignment feedback field and in these cases the Word Import button does not any anything. 

Steps to reproduce: 
1. Create an assignement with with feedbackcomments enabled. 
2. As a student upload an assignment. 
3. As teacher open the grader interface for the assignment and find the Feedback comments text field. 
4. Press the Word import button. 

Result: Nothing happens 
Expected result: Since the field does not support upload of files, the Word import button should be removed.

**Comment by ecampbell** [comment]
Thanks for reporting this bug so clearly. I was aware of the issue already, but didn't understand what to do to fix it. I was able to copy code from the atto_managefiles plugin to disable the Word Import button when appropriate. I released version 1.3.5 to fix it.
