### ISSUE TITLE
word import inserting contents into wrong element (via file picker)

### ISSUE THREAD

**Issue by keevan** [ecampbell/moodle-atto_wordimport#25]
When using wordimport, once a file has been selected, and "Upload this file" button is clicked. You can replicate this issue by clicking intensively on any other HTML element on the page, as long as it is not the editor.

This causes the handling to insert the contents, at the focus point at the time, which might not be the editor, which produces the issue.

**Comment by ecampbell** [comment]
Many thanks for this code, I have now merged it into v1.4.3, for Moodle version 4.1 and upwards. Apologies for the delay in responding.
