### ISSUE TITLE
Can't make it working here

### ISSUE THREAD

**Issue by mudrd8mz** [ecampbell/moodle-atto_wordimport#4]
I am trying to test the functionality of the plugin. When clicking the icon, I am asked to provide a file. I upload a DOCX file but nothing happens then, no content appears in the Atto and no explanation message is given.

**Comment by ecampbell** [comment]
I'm not sure what this problem might be, but if you could send me the sample file you used, that would help me. I found the file www.easychair.org/publications/easychair.docx on the web and successfully imported that on my test server.

**Comment by mudrd8mz** [comment]
OK, this was a problem on my side. It turned out I did not have the XSL extension available in my PHP. Your plugin correctly declares it as required and it was reported in the server environment check. I still had troubles importing a test DOCX file created in my LibreOffice, but I was able to import the example you mention above. I believe we can close this now.
