### ISSUE TITLE
Multiple issues with the atto/wordimport:visible

### ISSUE THREAD

**Issue by mudrd8mz** [ecampbell/moodle-atto_wordimport#7]
- The capability name is not localised (as be simply seen from the role editing screens).
- The capability is not actually checked
- The overall design of capability is a bit questionable as the same user can have different roles in different contexts. And it seems a bit weird to have the editor button visible in certain contexts and not in others. In fact, no standard Atto plugin uses the permission checks.

**Comment by ecampbell** [comment]
I have removed the capability setting as it is unnecessary.
